/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import Script from "next/script";
import "./globals.css";
import { Header, Layout, LayoutParts, ThemeProvider } from "@/ui/components";
import { Inter } from "next/font/google";

import "@code-hike/mdx/dist/index.css";

const inter = Inter({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInline = `
const LOCAL_KEY = "gf-theme";
const initialTheme = () => {
  const getLocalStorage = (window.localStorage.getItem(LOCAL_KEY)) || "";
  if (getLocalStorage) return getLocalStorage;
  return 'dark';
};
document.body.classList.add(initialTheme());
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} dark font-sans`}>
        <Script
          id="theme"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeInline }}
        />
        <ThemeProvider>
          <Layout>
            <Header />
            <Layout.Part type={LayoutParts.Middle}>
              <Layout.Container>
                <Layout.Part className="" type={LayoutParts.Main}>
                  {children}
                </Layout.Part>
              </Layout.Container>
            </Layout.Part>
            <Layout.Part type={LayoutParts.Footer}>
              <Layout.Container>Footer</Layout.Container>
            </Layout.Part>
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
