/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import Script from "next/script";
import "./globals.css";
import { ThemeProvider } from "@/ui/components";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInline = `
const LOCAL_KEYG = "gf-theme";
const COLOR_SCHEME_QUERY = "(prefers-color-scheme: light)";
const Themes = {
  light: 'light',
  dark: 'dark',
}
const prefersLight = window.matchMedia(COLOR_SCHEME_QUERY).matches;
const initialTheme = () => {
  const getLocalStorage = (window.localStorage.getItem(LOCAL_KEYG)) || "";
  if (getLocalStorage) return getLocalStorage;
  if (prefersLight) return Themes.light;
  return Themes.dark;
};
document.body.classList.add(initialTheme());
console.log("inline theme script");
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Script
          id="theme"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeInline }}
        />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
